from __future__ import annotations

import tempfile
import unittest
from pathlib import Path

from tools.governance.template_scaffold import (
    realize_repository_scaffold,
    render_scaffold_surface,
)


def _protected_region(text: str) -> str:
    start = text.index("# BEGIN GENERATED REGION")
    end = text.index("# END GENERATED REGION") + len("# END GENERATED REGION")
    return text[start:end]


class SchedulerGeneratedSurfaceConformanceTests(unittest.TestCase):
    def test_scheduler_generated_surfaces_match_canonical_renderer_across_certified_compositions(self) -> None:
        cases = (
            ["scheduler"],
            ["scheduler", "cli-worker"],
            ["scheduler", "monorepo"],
            ["scheduler", "python-package"],
            ["scheduler", "cli-worker", "monorepo"],
            ["scheduler", "cli-worker", "python-package"],
        )

        for overlays in cases:
            with self.subTest(overlays=overlays):
                with tempfile.TemporaryDirectory() as tmp:
                    realize_repository_scaffold(
                        "universal-base",
                        Path(tmp),
                        overlays=list(overlays),
                        include_optional=False,
                    )
                    for surface in ("scheduler/schedule.py", "scheduler/scheduler_runtime.py"):
                        actual = (Path(tmp) / surface).read_text()
                        self.assertEqual(render_scaffold_surface(surface), actual)

    def test_scheduler_generated_surfaces_expose_explicit_protected_regions(self) -> None:
        for surface in ("scheduler/schedule.py", "scheduler/scheduler_runtime.py"):
            with self.subTest(surface=surface):
                text = render_scaffold_surface(surface)
                self.assertIn("# GENERATED BY TEMPLATE: scheduler-overlay", text)
                self.assertIn("# DO NOT MODIFY GENERATED REGION DIRECTLY", text)
                self.assertIn("# BEGIN GENERATED REGION", text)
                self.assertIn("# END GENERATED REGION", text)
                self.assertIn("Custom extension boundary", text)
                self.assertLess(text.index("# BEGIN GENERATED REGION"), text.index("# END GENERATED REGION"))
                self.assertLess(text.index("# END GENERATED REGION"), text.index("Custom extension boundary"))

    def test_scheduler_drift_inside_protected_region_is_detectable(self) -> None:
        canonical = render_scaffold_surface("scheduler/schedule.py")
        drifted = canonical.replace('"cron": "0 * * * *"', '"cron": "*/5 * * * *"', 1)
        self.assertNotEqual(canonical, drifted)
        self.assertNotEqual(_protected_region(canonical), _protected_region(drifted))

    def test_scheduler_custom_extension_outside_protected_region_preserves_generated_truth(self) -> None:
        canonical = render_scaffold_surface("scheduler/scheduler_runtime.py")
        customized = canonical + "\n\ndef install_repository_runtime_hook():\n    return 'custom'\n"
        self.assertEqual(_protected_region(canonical), _protected_region(customized))
        self.assertNotEqual(canonical, customized)


if __name__ == "__main__":
    unittest.main()
